name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:          
  Continuous-Deployment:
    needs: build-and-push-ecr-image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List Files
        run: |
          echo "Cloned files are in the following directory:"
          pwd
          ls -al /home/runner/work/my-app/my-app  # Change this path based on your repo name
